childBlocks: ''
field: fa112548-c36b-46b2-901a-839be3825ce8 # Content builder
fieldLayouts:
  8b30f595-c0c0-4d6f-b143-befe57a83bcd:
    tabs:
      -
        elements:
          -
            style: warning
            tip: 'Editing this block requires admin privileges'
            type: craft\fieldlayoutelements\Tip
          -
            fieldUid: dbffb804-36fc-4aed-b00d-52a8888f8af4 # Block custom content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
handle: customContent
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Custom content'
sortOrder: 4
topLevel: true
