childBlocks: ''
field: fa112548-c36b-46b2-901a-839be3825ce8 # Content builder
fieldLayouts:
  609d742c-38ce-4df5-bfc3-89a86cfffcf3:
    tabs:
      -
        elements:
          -
            fieldUid: 6cbd429a-eb7f-435a-a392-ac75de54825e # Block title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 6f5abd76-ca33-4479-b677-cdc57f4ff2d6 # Block video url
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Main
        sortOrder: 1
handle: video
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Video
sortOrder: 3
topLevel: true
